# Generated by Django 5.0.1 on 2024-11-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.TextField(max_length=10),
        ),
    ]
