# Generated by Django 5.0.1 on 2024-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
