# Generated by Django 5.0.1 on 2024-11-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_date',
        ),
    ]
